--- 
- merb-core (= 1.0.3, runtime)
- merb-gen (= 1.0.3, runtime)
- extlib (>= 0.9.8, runtime)
- erubis (>= 2.6.2, runtime)
- rake (>= 0, runtime)
- json_pure (>= 0, runtime)
- rspec (>= 0, runtime)
- rack (>= 0, runtime)
- mime-types (>= 0, runtime)
- thor (>= 0.9.7, runtime)
- webrat (>= 0.3.1, development)
- mongrel (>= 1.1.4, runtime)
- ebb (>= 0.3.2, runtime)
- thin (>= 1.0.0, runtime)
- mocha (>= 0.9.3, runtime)

- merb_datamapper (>= 1.0.3, runtime) #Note the underscore
- merb-action-args (>= 1.0.3, runtime)
- merb-assets (>= 1.0.3, runtime)  
- merb-cache (>= 1.0.3, runtime)   
- merb-helpers (>= 1.0.3, runtime) 
- merb-mailer (>= 1.0.3, runtime)  
- merb-slices (>= 1.0.3, runtime)  
- merb-auth-core (>= 1.0.3, runtime)
- merb-auth-more (>= 1.0.3, runtime)
- merb-auth-slice-password (>= 1.0.3, runtime)
- merb-param-protection (>= 1.0.3, runtime)
- merb-exceptions (>= 1.0.3, runtime)
- merb-haml (>= 1.0.3, runtime)

- dm-core (>= 0.9.7, runtime)         
- dm-aggregates (>= 0.9.7, runtime)   
- dm-migrations (>= 0.9.7, runtime)   
- dm-timestamps (>= 0.9.7, runtime)   
- dm-types (>= 0.9.7, runtime)        
- dm-validations (>= 0.9.7, runtime)
- do_mysql (>= 0.9.9, runtime)  #Note the underscore
